[build]
target = "thumbv7m-none-eabi"

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = 'probe-rs run --chip stm32f103c6'

[env]
DEFMT_LOG = "debug"

[unstable]
build-std = ["core"]
build-std-features = ["panic_immediate_abort"]
